//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB_DAL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Doctors = new HashSet<Doctor>();
            this.Donors = new HashSet<Donor>();
            this.Receivers = new HashSet<Receiver>();
        }
    
        public int C_Id { get; set; }
        public string City_Name { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<Donor> Donors { get; set; }
        public virtual ICollection<Receiver> Receivers { get; set; }
    }
}
