//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB_DAL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Doctor_Donor = new HashSet<Doctor_Donor>();
            this.Doctor_Receiver = new HashSet<Doctor_Receiver>();
        }
    
        public int Doc_Id { get; set; }
        public string Name { get; set; }
        public string Fath_Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string CNIC { get; set; }
        public string Contact_No { get; set; }
        public bool Gender { get; set; }
        public string Address { get; set; }
        public int C_ID { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Doctor_Donor> Doctor_Donor { get; set; }
        public virtual ICollection<Doctor_Receiver> Doctor_Receiver { get; set; }
    }
}
