//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB_DAL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Donor
    {
        public int Doctor_ID { get; set; }
        public int Donor_ID { get; set; }
        public System.DateTime Date_Time { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
